name: 'Setup'
description: 'Set up Buildx and authenticate to AWS ECR'
inputs:
  aws-role-arn:
    required: true
  aws-region:
    required: true
  ecr-registry:
    required: true
  ecr-repository:
    required: true
outputs:
  image-name:
    value: ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ steps.create-short-sha.outputs.SHORT_SHA }}
  cache-name:
    value: ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:cache
runs:
  using: "composite"
  steps:
    # Stop docker so we can mount more space at /var/lib/docker
    - name: Stop docker
      run: sudo systemctl stop docker
      shell: bash
    # This creates a virtual volume at /var/lib/docker to maximize the size
    # As of 2/14/2024, this results in 97G for docker images
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        build-mount-path: '/var/lib/docker'
    - name: Start docker
      run: sudo systemctl start docker
      shell: bash
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
    - name: Create version file
      run: make version
      shell: bash
    - id: create-short-sha
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      shell: bash
